---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catalogue-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["catalogue-db-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: carts-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["carts-db-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list"]
  resourceNames: ["user-config"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["session-db-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orders-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["rabbitmq-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shipping-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["rabbitmq-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: queue-master-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["rabbitmq-secret"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-role
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]