apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

commonLabels:
  app.kubernetes.io/part-of: sock-shop
  app.kubernetes.io/component: microservice

resources:
  - carts
  - catalogue
  - frontend
  - orders
  - payment
  - queue-master
  - shipping
  - user
  

