apiVersion: v1
kind: Secret
metadata:
  name: carts-db-secret
  namespace: sock-shop
  labels:
    app.kubernetes.io/name: carts-db
    app.kubernetes.io/part-of: sock-shop
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: carts
  MONGO_INITDB_ROOT_PASSWORD: changeme
  SPRING_DATA_MONGODB_URI: "mongodb://carts:changeme@carts-db:27017/cartsdb?authSource=admin"

