apiVersion: v1
kind: Secret
metadata:
  name: catalogue-db-secret
  namespace: sock-shop
  labels:
    app: catalogue-db
    app.kubernetes.io/name: catalogue-db
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: changeme
