apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: sock-shop
  labels:
    app.kubernetes.io/name: orders-db
    app.kubernetes.io/part-of: sock-shop
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: orders
  MONGO_INITDB_ROOT_PASSWORD: changeme