apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: sock-shop
  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: changeme