apiVersion: v1
kind: Secret
metadata:
  name: session-db-secret
  namespace: sock-shop
  labels:
    app.kubernetes.io/name: session-db
    app.kubernetes.io/part-of: sock-shop
type: Opaque
stringData:
  REDIS_PASSWORD: "change-me"
  