apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: sock-shop
  labels:
    app: user-db
    app.kubernetes.io/name: user-db
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: users
  MONGO_INITDB_ROOT_PASSWORD: changeme
  MONGO_INITDB_DATABASE: users