apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

commonLabels:
  app: rabbitmq
  app.kubernetes.io/name: rabbitmq
  app.kubernetes.io/component: message-broker
  tier: infrastructure

resources:
  - statefulset.yaml
  - 20-rabbitmq-svc.yaml