apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-cred-access
spec:
  kprobes:
    - call: "fd_install"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "file"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Prefix"
              values:
                - "/etc/shadow"
                - "/etc/passwd"
                - "/root/.ssh"
                - "/.aws/credentials"
                - "/var/run/secrets/kubernetes.io"
                - "/proc/1/environ"
          matchActions:
            - action: Post  