apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

commonLabels:
  app: carts-db
  app.kubernetes.io/name: carts-db
  app.kubernetes.io/component: database
  tier: database

resources:
  - statefulset.yaml
  - 03-carts-db-temp-pvc.yaml
  - 04-carts-db-svc.yaml
